language: node_js

node_js: "12.13"

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "duraes-antonio-github"
    token: ${SONAR_TOKEN}

before_script:
  - git rm package-lock.json
  - yarn install

script:
  - sonar-scanner
