language: node_js

node_js:
  - node

branches:
  only:
    - master

before_script:
  - cd frontend
  - npm install -g --save-dev @angular/cli@latest
  - npm install -g --save-dev @angular-devkit/build-angular
  - npm install

script:
  - ng build --prod