language: node_js

node_js:
  - node

branches:
  only:
    - master

before_script:
  - cd frontend
  - npm install -g @angular/cli@latest
  - npm install -g @angular-devkit/build-angular
  - npm install -g sass
  - npm install

script:
  - ng build --prod