language: node_js

node_js:
  - node

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "duraes-antonio-github"

before_script:
  - cd frontend
  - npm install
  - npm install --save-dev node-sass

script:
  - ng build --prod
  - sonar-scanner