language: node_js

node_js:
  - node

branches:
  only:
    - master

before_script:
  - cd frontend
  - npm install
  - npm rebuild node-sass --force
  - npm install --save-dev node-sass

script:
  - ng build --prod