language: node_js

node_js:
  - node

branches:
  only:
    - master

before_script:
  - cd frontend
  - npm install -g @angular/cli
  - npm install -g @angular-devkit/build-angular --dev

script:
  - ng build --prod