language: node_js

node_js:
  - node

branches:
  only:
    - master

before_script:
  - cd frontend
  - yarn global add @angular/cli
  - yarn add @angular-devkit/build-angular --dev

script:
  - ng build --prod