'use strict';
export enum TypeNotification {
  PAYMENT_PENDENT,
  PAYMENT_CONFIRMED,
  PAYMENT_RETURNED,
  ORDER_PREPARED,
  ORDER_ON_DELIVERY,
  ORDER_DELIVERED,
  QUESTION_ANSWERED,
  PASSWORD_UPDATED
}
