export enum ETipoNotificacao {
  PAGAMENTO_PENDENTE,
  PAGAMENTO_CONFIRMADO,
  PAGAMENTO_DEVOLVIDO,
  COMPRA_SEPARADA,
  COMPRA_EM_ENTREGA,
  COMPRA_ENTREGUE,
  DUVIDA_RESPONDIDA,
  ATUALIZACAO_SENHA
}
